import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("Phase 7 stores only activity references and the six requested event types", async () => {
  const source = await readFile(new URL("../functions/api/[[path]].js", import.meta.url), "utf8");

  assert.match(source, /CREATE TABLE IF NOT EXISTS activity_events/);
  for (const type of [
    "started_work",
    "progress_reached",
    "completed_work",
    "favorited_work",
    "added_to_list",
    "created_list",
  ]) {
    assert.match(source, new RegExp(type));
  }
  assert.match(source, /FOREIGN KEY \(list_id\) REFERENCES user_lists\(id\) ON DELETE CASCADE/);
  assert.doesNotMatch(source, /activity_events[\s\S]{0,400}(work_title|cover_url|sentence|message) TEXT/i);
});

test("Phase 7 activity is generated by trusted existing mutations and not arbitrary client writes", async () => {
  const source = await readFile(new URL("../functions/api/[[path]].js", import.meta.url), "utf8");

  assert.match(source, /recordLibraryStatusActivity/);
  assert.match(source, /recordReadingActivity/);
  assert.match(source, /type: "favorited_work"/);
  assert.match(source, /type: "created_list"/);
  assert.match(source, /type: "added_to_list"/);
  assert.doesNotMatch(source, /request\.method === "POST" && path === "activity"/);
  assert.doesNotMatch(source, /createActivity\(/);
});

test("Phase 7 friends feed filters private users before serialization", async () => {
  const source = await readFile(new URL("../functions/api/[[path]].js", import.meta.url), "utf8");

  assert.match(
    source,
    /JOIN friendships f ON f\.user_id = \? AND f\.friend_id = e\.user_id[\s\S]*u\.profile_visibility = 'public'/,
  );
  assert.match(source, /ORDER BY e\.created_at DESC, e\.id DESC/);
});

test("Phase 7 adds activity to the existing modular profile system", async () => {
  const api = await readFile(new URL("../functions/api/[[path]].js", import.meta.url), "utf8");
  const types = await readFile(new URL("../src/types/index.ts", import.meta.url), "utf8");
  const editor = await readFile(
    new URL("../src/components/ProfileSectionEditor.tsx", import.meta.url),
    "utf8",
  );

  assert.match(api, /my_activity/);
  assert.match(api, /friends_activity/);
  assert.match(types, /"my_activity"/);
  assert.match(types, /"friends_activity"/);
  assert.match(editor, /نشاطي/);
  assert.match(editor, /نشاط الأصدقاء/);
});

test("Phase 7 does not introduce notifications, reactions, avatar library, or admin work", async () => {
  const migration = await readFile(new URL("../migrations/0007_activity.sql", import.meta.url), "utf8");

  assert.doesNotMatch(migration, /notification|reaction|comment|avatar|admin/i);
});
