-- Run outside requests. Existing pre-column caches require the preparatory ALTERs
-- generated by scripts/prepare-source-schema.py from a private local backup.
-- This does not change account schema_version or account/user data.
CREATE TABLE IF NOT EXISTS source_items (
  source_key TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  source_id TEXT NOT NULL,
  slug TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT '',
  url TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  cover_url TEXT NOT NULL DEFAULT '',
  description TEXT,
  status TEXT,
  genres_json TEXT NOT NULL DEFAULT '[]',
  updated_at INTEGER NOT NULL,
  first_seen_at INTEGER,
  UNIQUE(source, source_id)
);
CREATE TABLE IF NOT EXISTS source_chapter_seen (
  source_key TEXT NOT NULL,
  chapter_identity TEXT NOT NULL,
  chapter_number REAL,
  published_at TEXT,
  first_seen_at INTEGER NOT NULL,
  is_baseline INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (source_key, chapter_identity),
  FOREIGN KEY (source_key) REFERENCES source_items(source_key) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS source_sync_state (
  source TEXT PRIMARY KEY,
  last_started_at INTEGER NOT NULL DEFAULT 0
);
UPDATE source_items SET first_seen_at = updated_at WHERE first_seen_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_source_chapter_seen_release
  ON source_chapter_seen(first_seen_at DESC, source_key);
